---
- hosts: node0@172.31.31.23
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: I want to install webserver
    apt:
      name: apache2
      state: present
  
  - name: copy index file to node side
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: downloading internet files
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz
      dest: home/ubuntu/apache-tomcat-10.1.13.tar.gz
      force_basic_auth: yes