---
- hosts: node0@172.31.31.23
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: I want to install webserver
    apt:
      name: apache2
      state: present
  
  - name: copy index file to node side
    copy:
      src: index.html
      dest: /var/www/html/cafe