---
- hosts: node0@172.31.31.23
  become: yes
  vars: 
    myvars01: git                            # local variable
    myvars02: tree                           # local variable
  tasks:
    - name: Iwant to dispaly my vars01
      debug:
        msg: 
          -variable 1 is "{{myvars01}}"
           variable 2 is "{{myvars02}}"
           variable 3 is "{{myjavapackonubuntu}}"
