---
- hosts: all
  become: yes
  tasks :
   - name: installing apache2
     apt:
       name: apache2
       state: present
     when: ansible_os_family == 'Debian'            #ansible all -i myhosts -m setup -a filter="*family*" in master

   - name: running apache2 
     service :
       name: apache2
       state: started
     when: ansible_os_family == 'Debian'
   
   - name : installing webserver on redhat server
     ansible.builtin.dnf:                                  # it is equal to apt
       name: httpd
       state: present
     when: ansible_os_family == 'RedHat'

   - name: running server 
     service:
       name:  httpd
       state: started
     when: ansible_os_family == 'RedHat'
          