---
- hosts: all
  become: yes
  tasks :
   - name: installing apache2
     apt:
       name: apache2
       state: present

   - name: running apache2 
     service :
       name: apache2
       state: started
