---
- hosts: node0@172.31.31.23
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myresult                               # register stores output of command in variable

  - name: display first task result
    debug:
       msg: "{{myresult}}"                           # we can see stdout & stderr we can choose any of them to decide our next task

  - name: install git
    apt: 
      name: git
      state: present
    when: myresult.stderr ==""                        # we are selecting stderr from output of 'command'

  - name: instll tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !=""                        # This means error while executing command

             

  