---
- hosts: node0@172.31.31.23
  become: yes
  tasks:
    - name: execute linux command using playbook
      command: hostname -f
      register: myfirsttaskresult           # register stores output of command in variable 

    - name: debug 1st task result
      debug:
        msg: "{{myfirsttaskresult}}"        # we can see stdout & stderr we can choose any of them to decide our next task

    - name: install git                 # Deciding to install git or tree based on result of myfirsttaskresult
      apt:
        name: git
        state: present
      when: myfirsttaskresult.stderr==""  # we are selecting stderr from output of 'command'

    - name: install tree
      apt:
        name: tree
        state: present
      when: myfirsttaskresult.stderr!=""   # This means error while executing command