---
- name: downloading tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz
    dest: /home/ubuntu/
    force_basic_auth: yes

- name:  create a directory
  file: 
    path: /opt/tomcat  
    state: directory

- name: extract tar file
  command: sudo tar xzvf apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1
  creates: /opt/tomcat/LICENCE
   
# or we can use unarchive module
# name: Unarchive a file that needs to be downloaded (added in 2.0)
#  ansible.builtin.unarchive:
#    src: https://example.com/example.zip
#    dest: /opt/tomcat
#    remote_src: yes

    